version: "3.1"

services:
    discord-bot:
        image: ai-horde-bot
        restart: always
        depends_on:
            - database
        volumes:
            - ./config.json:/usr/config.json
        env_file:
            - .env

    database:
        image: mongo
        restart: always
        expose:
            - 27017
        volumes:
            - ./db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: changeme
