version: "3.1"

services:
    stable-horde-bot:
        image: stable-horde-bot
        restart: always
        depends_on:
            - mongo
        volumes:
            - ./config.json:/usr/src/config.json
        env_file:
            - .env

    mongo:
        image: mongo
        restart: always
        expose:
            - 27017
        volumes:
            - ./db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: changeme
