import {
    ActionRowBuilder,
    ButtonBuilder,
    ButtonInteraction,
    ButtonStyle,
    EmbedBuilder,
    TextChannel,
} from "discord.js";

import config from "../config.js";
import Models from "../types/models.js";

export default {
    async buttonHandler(
        interaction: ButtonInteraction,
        { User, Generation }: Models
    ) {
        await interaction.deferReply({ ephemeral: true });

        const user = await User.findById(interaction.user.id);

        if (!user) {
            await interaction.followUp(
                "You are not logged in. Please use /login in the server."
            );
            return;
        }

        if (interaction.user.id !== interaction.message.interaction?.user.id) {
            await interaction.followUp(
                "You can only submit your own generations."
            );
            return;
        }

        let imageEmbed;

        for (const embed of interaction.message.embeds) {
            if (embed.image) {
                imageEmbed = embed;
            }
        }

        if (!imageEmbed) {
            await interaction.followUp(
                "There was an error processing your submission."
            );
            return;
        }

        await interaction.followUp({
            content: "Your submission has been recorded.",
            ephemeral: true,
        });

        const channel = (await interaction.guild?.channels.fetch(
            config.event.channelId
        )) as TextChannel;

        await interaction.message.edit({
            components: [
                new ActionRowBuilder<ButtonBuilder>().addComponents(
                    new ButtonBuilder()
                        .setCustomId("event")
                        .setEmoji("🎟️")
                        .setLabel("Submitted")
                        .setStyle(ButtonStyle.Primary)
                        .setDisabled(true)
                ),
            ],
        });

        if (channel) {
            const generation = await Generation.findById(
                interaction.message.id
            );

            channel.send({
                embeds: [
                    new EmbedBuilder()
                        .setTitle("New Submission")
                        .setDescription(
                            `Generated by <@${generation?.author}>\nPrompt: ${generation?.prompt}\nStyle: ${generation?.style}\n[Jump to Message](${interaction.message.url})`
                        )
                        .setColor("Blue")
                        .setImage(imageEmbed.image?.url || ""),
                ],
            });
        }
    },
};
